name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: instanacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image to ACR
      run: |
        docker build -t instanacr.azurecr.io/instanapp:latest .
        docker push instanacr.azurecr.io/instanapp:latest

    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: rg-container
        containerAppName: instanapp
        imageToDeploy: instanacr.azurecr.io/instanapp:latest
